# Docker Compose Configuration
# visit https://docs.docker.com/compose/

version: '3.8'
services:
  app:
    container_name: backend
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - '8000:8000'
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: 'user'
      MONGO_INITDB_ROOT_PASSWORD: '12345'
      MONGO_INITDB_DATABASE: 'quizdb'
    ports:
      - '27017:27017'
    restart: always